version: "3.8"
services:
  dev-db:
    image: "postgres:16.3-alpine3.20"
    ports:
      - 5437:5432
    expose:
      - "5437"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=issue-tracker
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
